# Generated by Django 3.0.2 on 2020-09-11 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=60)),
                ('experience', models.CharField(max_length=60)),
                ('prefer', models.CharField(max_length=60)),
                ('online', models.BooleanField()),
                ('profile', models.FileField(upload_to='')),
                ('subject', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
